AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'metadata.rb'
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/**/*.rb'

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only
